C:\fess-15.4.0\app\WEB-INF\classes\auth_login.conf
spnego-client {
    com.sun.security.auth.module.Krb5LoginModule required;
};

spnego-server {
    com.sun.security.auth.module.Krb5LoginModule required
    doNotPrompt=true
    principal="HTTP/fess.contoso.local@CONTOSO.LOCAL"
    keyTab="C\:/fess-15.4.0/app/WEB-INF/classes/fess.keytab"
    storeKey=true
    useKeyTab=true
    isInitiator=false
    refreshKrb5Config=true
    storePass=true
    debug=true;
};
