krb5.conf
[libdefaults]
    default_realm = CONTOSO.LOCAL
    default_tkt_enctypes = aes256-cts aes128-cts rc4-hmac des3-cbc-sha1 des-cbc-md5 des-cbc-crc
    default_tgs_enctypes = aes256-cts aes128-cts rc4-hmac des3-cbc-sha1 des-cbc-md5 des-cbc-crc
    permitted_enctypes   = aes256-cts aes128-cts rc4-hmac des3-cbc-sha1 des-cbc-md5 des-cbc-crc

[realms]
    CONTOSO.LOCAL = {
        kdc = SRV-DC1.CONTOSO.LOCAL
        default_domain = CONTOSO.LOCAL
    }

[domain_realm]
    contoso.local = CONTOSO.LOCAL
    .contoso.local = CONTOSO.LOCAL
