C:\fess-15.4.0\app\WEB-INF\conf\system.properties
#system.properties
#Sun Feb 15 23:44:43 CET 2026
append.query.parameter=false
crawling.incremental=true
crawling.thread.count=5
csv.file.encoding=UTF-8
day.for.cleanup=3
failure.countthreshold=-1
ldap.account.filter=(&(objectClass\=user)(sAMAccountName\=%s))
ldap.admin.security.credentials={cipher}4f67bb1f41ccf2cec2bf9eb403d322f8
ldap.admin.security.principal=fess@contoso.local
ldap.base.dn=dc\=contoso,dc\=local
ldap.group.filter=(member\:1.2.840.113556.1.4.1941\:\=%s)
ldap.memberof.attribute=memberOf
ldap.provider.url=ldap\://contoso.local\:389
ldap.security.principal=%s@contoso.local
login.link.enabled=true
login.required=true
purge.by.bots=Crawler,crawler,Bot,bot,Slurp,Yeti,Baidu,Steeler,ichiro,hotpage,Feedfetcher,ia_archiver,Y\!J-BRI,Google Desktop,Seznam,Tumblr,YandexBot,Chilkat,CloudFront,Mediapartners,MSIE 6
purge.joblog.day=-1
purge.searchlog.day=-1
purge.suggest.searchlog.day=30
purge.userinfo.day=-1
result.collapsed=false
search.log=true
spnego.allow.basic=true
spnego.allow.delegation=false
spnego.allow.localhost=true
spnego.allow.unsecure.basic=true
spnego.initialized=true
spnego.krb5.conf=krb5.conf
spnego.logger.level=7
spnego.login.client.module=spnego-client
spnego.login.conf=auth_login.conf
spnego.login.server.module=spnego-server
spnego.preauth.password=Pa$$w0rd35
spnego.preauth.username=fessuser@contoso.local
spnego.prompt.ntlm=false
sso.type=spnego
storage.region=us-east-1
storage.type=auto
suggest.document=true
suggest.searchlog=true
thumbnail.enabled=false
user.favorite=false
user.info=true
web.api.json=true
web.api.popularword=true
